#!/usr/bin/env node
/* Generate card-tiers.js (window.CARDTIER) from content/card-tiers.json.
 *
 * Mirrors the mcq-why.js pattern: a served, precached JS file keyed by the
 * card's EXACT front text — the same key the content pipeline de-dupes on.
 * Run after editing content/card-tiers.json, then rebuild + bump versions.
 *
 *   node scripts/build_card_tiers.mjs
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const SRC = path.join(ROOT, 'content/card-tiers.json');
const OUT = path.join(ROOT, 'card-tiers.js');

const data = JSON.parse(fs.readFileSync(SRC, 'utf8'));
const tiers = data.tiers || {};

// Validate before writing — a bad tier value would silently break the filter.
const counts = { 1: 0, 2: 0, 3: 0 };
for (const [front, t] of Object.entries(tiers)) {
  if (t !== 1 && t !== 2 && t !== 3) throw new Error(`bad tier ${JSON.stringify(t)} for: ${front.slice(0, 60)}`);
  counts[t]++;
}

// Cross-check against the live card content so a renamed front can't go unnoticed.
const cardFiles = fs.readdirSync(path.join(ROOT, 'content')).filter(f => f.endsWith('.cards.json'));
const fronts = new Set();
for (const f of cardFiles) {
  for (const c of JSON.parse(fs.readFileSync(path.join(ROOT, 'content', f), 'utf8'))) fronts.add(c.f);
}
const untiered = [...fronts].filter(f => !(f in tiers));
const orphaned = Object.keys(tiers).filter(f => !fronts.has(f));
if (orphaned.length) {
  console.warn(`WARNING: ${orphaned.length} tier entr${orphaned.length === 1 ? 'y matches' : 'ies match'} no current card (front text changed?):`);
  orphaned.slice(0, 5).forEach(f => console.warn('   - ' + f.slice(0, 90)));
}
if (untiered.length) {
  console.warn(`WARNING: ${untiered.length} card(s) have no tier — they pass EVERY tier filter by design:`);
  untiered.slice(0, 5).forEach(f => console.warn('   - ' + f.slice(0, 90)));
}

const total = counts[1] + counts[2] + counts[3];
const pct = n => (100 * n / total).toFixed(1) + '%';
const banner = `/* card-tiers.js — GENERATED by scripts/build_card_tiers.mjs. Do not hand-edit.
 * Source of truth: content/card-tiers.json
 *
 * window.CARDTIER maps a flashcard's EXACT front text -> exam-likelihood tier:
 *   1 = high yield (most likely on the CFP Board exam)
 *   2 = moderate (somewhat likely)
 *   3 = low yield (course/textbook detail outside the Board's tested topics)
 *
 * Judgment against the CFP Board Principal Knowledge Topics + blueprint domain
 * weights — an informed prioritization, NOT an official CFP Board answer key.
 * Tier 3 is not wrong or useless: the FP511/FP512 module exams still test it.
 *
 * A card with no entry here is "untiered" and passes EVERY tier filter, so new
 * course content is never silently hidden from study before it has been tiered.
 *
 * ${total} cards — T1 ${counts[1]} (${pct(counts[1])}) · T2 ${counts[2]} (${pct(counts[2])}) · T3 ${counts[3]} (${pct(counts[3])})
 */
`;

// One key per line keeps the diff readable when a single card is re-tiered.
const body = Object.entries(tiers)
  .map(([f, t]) => ' ' + JSON.stringify(f) + ': ' + t)
  .join(',\n');

fs.writeFileSync(OUT, banner + 'window.CARDTIER = {\n' + body + '\n};\n');
console.log(`wrote card-tiers.js — ${total} cards (T1 ${counts[1]} / T2 ${counts[2]} / T3 ${counts[3]})`);
